/*
CREATE USER forum IDENTIFIED BY pwd;
GRANT CONNECT, RESOURCE, DBA to forum;
*/

/*==============================================================*/
/* Table : UTILISATEUR                                          */
/*==============================================================*/
CREATE TABLE UTILISATEUR  (
   IDUTILISATEUR        INTEGER                    NOT NULL,
   PSEUDO               VARCHAR2(100),
   MOTDEPASSE           VARCHAR2(100),
   NOM                  VARCHAR2(100),
   PRENOM               VARCHAR2(100),
   DATENAISSANCE        DATE,
   TYPEUTILISATEUR      VARCHAR2(100),
   MAIL                 VARCHAR2(100),
   CONSTRAINT PK_UTILISATEUR PRIMARY KEY (IDUTILISATEUR)
);

--insert into UTILISATEUR values(SEQ_UTILISATEUR.nextval, '...');
/*==============================================================*/
/* Table : HISTORIQUE                                           */
/*==============================================================*/
CREATE TABLE HISTORIQUE  (
   IDHISTORIQUE         INTEGER                         NOT NULL,
   DATECONNEXION        DATE,
   IDUTILISATEUR        INTEGER                         NOT NULL,
   CONSTRAINT PK_HISTORIQUE PRIMARY KEY (IDHISTORIQUE)
);

/*==============================================================*/
/* Table : CATEGORIE                                           */
/*==============================================================*/
CREATE TABLE CATEGORIE  (
   IDCATEGORIE          INTEGER                         NOT NULL,
   TITRE                VARCHAR2(100),
   CONSTRAINT PK_CATEGORIE PRIMARY KEY (IDCATEGORIE)
);

/*==============================================================*/
/* Table : SOUSCATEGORIE                                        */
/*==============================================================*/
CREATE TABLE SOUSCATEGORIE  (
   IDSOUSCATEGORIE      INTEGER                         NOT NULL,
   IDCATEGORIE          INTEGER                         NOT NULL,
   TITRE                VARCHAR2(100),
   CONSTRAINT PK_SOUSCATEGORIE PRIMARY KEY (IDSOUSCATEGORIE)
);

/*==============================================================*/
/* Table : SUJET                                                */
/*==============================================================*/
CREATE TABLE SUJET  (
   IDSUJET              INTEGER                         NOT NULL,
   IDSOUSCATEGORIE      INTEGER                         NOT NULL,
   TITRE                VARCHAR2(200),
   DATESUJET            DATE,
   IDUTILISATEUR        INTEGER                         NOT NULL,
   CONSTRAINT PK_SUJET PRIMARY KEY (IDSUJET)
);

/*==============================================================*/
/* Table : COMMENTAIRE                                          */
/*==============================================================*/
CREATE TABLE COMMENTAIRE  (
   IDCOMMENTAIRE        INTEGER                         NOT NULL,
   IDSUJET              INTEGER                         NOT NULL,
   TEXTE                VARCHAR2(1000),
   DATECOMMENTAIRE      DATE,
   IDUTILISATEUR        INTEGER                         NOT NULL,
   CONSTRAINT PK_COMMENTAIRE PRIMARY KEY (IDCOMMENTAIRE)
);

/*==============================================================*/
/* Table : ACTUALITE                                            */
/*==============================================================*/
CREATE TABLE ACTUALITE  (
   IDACTUALITE          INTEGER                         NOT NULL,
   TITRE                VARCHAR2(100)                   NOT NULL,
   DESCRIPTION          VARCHAR2(1000)                  NOT NULL,
   CONSTRAINT PK_ACTUALITE PRIMARY KEY (IDACTUALITE)
);

/*==============================================================*/
/* FOREIGN KEY                                                  */
/*==============================================================*/

ALTER TABLE HISTORIQUE
   ADD CONSTRAINT FK_HISTORIQUE_UTILISATEUR FOREIGN KEY (IDUTILISATEUR)
      REFERENCES UTILISATEUR (IDUTILISATEUR);

ALTER TABLE SOUSCATEGORIE
   ADD CONSTRAINT FK_SOUSCATEGORIE_CATEGORIE FOREIGN KEY (IDCATEGORIE)
      REFERENCES CATEGORIE (IDCATEGORIE);
      
ALTER TABLE SUJET
   ADD CONSTRAINT FK_SUJET_SOUSCATEGORIE FOREIGN KEY (IDSOUSCATEGORIE)
      REFERENCES SOUSCATEGORIE (IDSOUSCATEGORIE);
      
ALTER TABLE SUJET
   ADD CONSTRAINT FK_SUJET_UTILISATEUR FOREIGN KEY (IDUTILISATEUR)
      REFERENCES UTILISATEUR (IDUTILISATEUR);
      
ALTER TABLE COMMENTAIRE
   ADD CONSTRAINT FK_COMMENTAIRE_SUJET FOREIGN KEY (IDSUJET)
      REFERENCES SUJET (IDSUJET);
      
ALTER TABLE COMMENTAIRE
   ADD CONSTRAINT FK_COMMENTAIRE_UTILISATEUR FOREIGN KEY (IDUTILISATEUR)
      REFERENCES UTILISATEUR (IDUTILISATEUR);
      
/*==============================================================*/
/* SEQUENCES                                                    */
/*==============================================================*/

--ON CREE UNE SEQUENCE POUR L'ID
CREATE SEQUENCE SEQ_UTILISATEUR   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HISTORIQUE    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORIE     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOUSCATEGORIE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUJET         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COMMENTAIRE   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACTUALITE     START WITH 1 INCREMENT BY 1;

/*==============================================================*/
/* INSERT INTO                                                  */
/*==============================================================*/

INSERT INTO UTILISATEUR VALUES(SEQ_UTILISATEUR.NEXTVAL, 'Adista', 'test', 'DI STASIO', 'Anthony', '09/07/1994', 'Admin', 'anthony.distasio@hotmail.com');
INSERT INTO UTILISATEUR VALUES(SEQ_UTILISATEUR.NEXTVAL, 'Cwotousse', 'test', 'MOUSTY', 'Adrien', '16/12/1992', 'Admin', 'moustyadrien@hotmail.com');

INSERT INTO CATEGORIE VALUES(SEQ_CATEGORIE.NEXTVAL, 'Sports');
INSERT INTO CATEGORIE VALUES(SEQ_CATEGORIE.NEXTVAL, 'Jeux vidéos');
INSERT INTO CATEGORIE VALUES(SEQ_CATEGORIE.NEXTVAL, 'Technologie');
INSERT INTO CATEGORIE VALUES(SEQ_CATEGORIE.NEXTVAL, 'Blabla');

INSERT INTO SOUSCATEGORIE VALUES(SEQ_SOUSCATEGORIE.NEXTVAL, 1, 'Football');
INSERT INTO SOUSCATEGORIE VALUES(SEQ_SOUSCATEGORIE.NEXTVAL, 1, 'Cyclisme');
INSERT INTO SOUSCATEGORIE VALUES(SEQ_SOUSCATEGORIE.NEXTVAL, 1, 'Handball');
INSERT INTO SOUSCATEGORIE VALUES(SEQ_SOUSCATEGORIE.NEXTVAL, 1, 'Basketball');
INSERT INTO SOUSCATEGORIE VALUES(SEQ_SOUSCATEGORIE.NEXTVAL, 1, 'Boxe');
INSERT INTO SOUSCATEGORIE VALUES(SEQ_SOUSCATEGORIE.NEXTVAL, 1, 'Hockey');


/*==============================================================*/
/* PROCEDURES STOCKEES - UTILISATEUR                            */
/*==============================================================*/
create or replace PROCEDURE INSERTUTILISATEUR(
	   P_PSEUDO IN UTILISATEUR.PSEUDO%TYPE,
	   P_MOTDEPASSE IN UTILISATEUR.MOTDEPASSE%TYPE,
     P_NOM IN UTILISATEUR.NOM%TYPE,
     P_PRENOM IN UTILISATEUR.PRENOM%TYPE,
     P_DATENAISSANCE IN UTILISATEUR.DATENAISSANCE%TYPE,
     P_TYPE IN UTILISATEUR.TYPEUTILISATEUR%TYPE,
	   P_MAIL IN UTILISATEUR.MAIL%TYPE)
IS
BEGIN
  INSERT INTO UTILISATEUR
  VALUES (SEQ_UTILISATEUR.NEXTVAL, P_PSEUDO, P_MOTDEPASSE, P_NOM, P_PRENOM, P_DATENAISSANCE, P_TYPE, P_MAIL);
  
  COMMIT;
END;

create or replace PROCEDURE DELETEUTILISATEUR(
	   P_PSEUDO IN UTILISATEUR.PSEUDO%TYPE)
IS
BEGIN
  DELETE FROM UTILISATEUR
  WHERE P_PSEUDO = PSEUDO;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATEUTILISATEUR(
	   P_MOTDEPASSE IN UTILISATEUR.MOTDEPASSE%TYPE,
     P_NOM IN UTILISATEUR.NOM%TYPE,
     P_PRENOM IN UTILISATEUR.PRENOM%TYPE,
     P_DATENAISSANCE IN UTILISATEUR.DATENAISSANCE%TYPE,
     P_TYPE IN UTILISATEUR.TYPEUTILISATEUR%TYPE,
	   P_MAIL IN UTILISATEUR.MAIL%TYPE,
     P_PSEUDO IN UTILISATEUR.PSEUDO%TYPE)
IS
BEGIN
  UPDATE UTILISATEUR
  SET MOTDEPASSE = P_MOTDEPASSE, NOM = P_NOM, PRENOM = P_PRENOM, DATENAISSANCE = P_DATENAISSANCE, TYPEUTILISATEUR = P_TYPE, MAIL = P_MAIL
  WHERE PSEUDO = P_PSEUDO;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTUTILISATEUR(
     -- PARAMETRE ENTRANT
	   P_IDUTILISATEUR IN UTILISATEUR.IDUTILISATEUR%TYPE,
     -- LES PARAMETRES SORTANTS
	   O_PSEUDO OUT UTILISATEUR.PSEUDO%TYPE,
	   O_MOTDEPASSE OUT UTILISATEUR.MOTDEPASSE%TYPE,
	   O_NOM OUT UTILISATEUR.NOM%TYPE,
     O_PRENOM OUT UTILISATEUR.PRENOM%TYPE,
     O_DATENAISSANCE OUT UTILISATEUR.DATENAISSANCE%TYPE,
     O_TYPE OUT UTILISATEUR.TYPEUTILISATEUR%TYPE,
     O_MAIL OUT UTILISATEUR.MAIL%TYPE)
IS
BEGIN
  SELECT PSEUDO, MOTDEPASSE, NOM, PRENOM, DATENAISSANCE, TYPEUTILISATEUR, MAIL
  INTO O_PSEUDO,  O_MOTDEPASSE, O_NOM, O_PRENOM, O_DATENAISSANCE, O_TYPE, O_MAIL
  FROM UTILISATEUR WHERE IDUTILISATEUR = P_IDUTILISATEUR;
END;

create or replace PROCEDURE GETLISTUTILISATEUR(
	   CUR_UTILISATEUR OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_UTILISATEUR FOR
  SELECT * FROM UTILISATEUR;
END;

/*==============================================================*/
/* PROCEDURES STOCKEES - ACTUALITE                              */
/*==============================================================*/
create or replace PROCEDURE INSERTACTUALITE(
	   P_TITRE IN ACTUALITE.TITRE%TYPE,
	   P_DESCRIPTION IN ACTUALITE.DESCRIPTION%TYPE)
IS
BEGIN
  INSERT INTO ACTUALITE
  VALUES (SEQ_ACTUALITE.NEXTVAL, P_TITRE, P_DESCRIPTION);
  
  COMMIT;
END;

create or replace PROCEDURE DELETEACTUALITE(
	   P_TITRE IN ACTUALITE.TITRE%TYPE,
     P_DESCRIPTION IN ACTUALITE.DESCRIPTION%TYPE)
IS
BEGIN
  DELETE FROM ACTUALITE
  WHERE P_TITRE = TITRE AND P_DESCRIPTION = DESCRIPTION;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATEACTUALITE(
     P_IDACTUALITE IN ACTUALITE.IDACTUALITE%TYPE,
	   P_TITRE IN ACTUALITE.TITRE%TYPE,
     P_DESCRIPTION IN ACTUALITE.DESCRIPTION%TYPE)
IS
BEGIN
  UPDATE ACTUALITE
  SET TITRE = P_TITRE, DESCRIPTION = P_DESCRIPTION
  WHERE IDACTUALITE = P_IDACTUALITE;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTACTUALITE(
     -- PARAMETRE ENTRANT
	   P_IDACTUALITE IN ACTUALITE.IDACTUALITE%TYPE,
     -- LES PARAMETRES SORTANTS
	   O_TITRE OUT ACTUALITE.TITRE%TYPE,
	   O_DESCRIPTION OUT ACTUALITE.DESCRIPTION%TYPE)
IS
BEGIN
  SELECT TITRE, DESCRIPTION
  INTO O_TITRE,  O_DESCRIPTION
  FROM ACTUALITE WHERE IDACTUALITE = P_IDACTUALITE;
END;

create or replace PROCEDURE GETLISTACTUALITE(
	   CUR_ACTUALITE OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_ACTUALITE FOR
  SELECT * FROM ACTUALITE;
END;

/*==============================================================*/
/* PROCEDURES STOCKEES - CATEGORIE                              */
/*==============================================================*/
create or replace PROCEDURE INSERTCATEGORIE(
	   P_TITRE IN CATEGORIE.TITRE%TYPE)
IS
BEGIN
  INSERT INTO CATEGORIE
  VALUES (SEQ_CATEGORIE.NEXTVAL, P_TITRE);
  
  COMMIT;
END;

create or replace PROCEDURE DELETECATEGORIE(
	   P_TITRE IN CATEGORIE.TITRE%TYPE)
IS
BEGIN
  DELETE FROM CATEGORIE
  WHERE P_TITRE = TITRE;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATECATEGORIE(
     P_IDCATEGORIE IN CATEGORIE.IDCATEGORIE%TYPE,
	   P_TITRE IN CATEGORIE.TITRE%TYPE)
IS
BEGIN
  UPDATE CATEGORIE
  SET TITRE = P_TITRE
  WHERE IDCATEGORIE = P_IDCATEGORIE;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTCATEGORIE(
     -- PARAMETRE ENTRANT
	   P_IDCATEGORIE IN CATEGORIE.IDCATEGORIE%TYPE,
     -- LES PARAMETRES SORTANTS
	   O_TITRE OUT CATEGORIE.TITRE%TYPE)
IS
BEGIN
  SELECT TITRE
  INTO O_TITRE
  FROM CATEGORIE WHERE IDCATEGORIE = P_IDCATEGORIE;
END;

create or replace PROCEDURE GETLISTCATEGORIE(
	   CUR_CATEGORIE OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_CATEGORIE FOR
  SELECT * FROM CATEGORIE;
END;

/*==============================================================*/
/* PROCEDURES STOCKEES - SOUSCATEGORIE                          */
/*==============================================================*/
create or replace PROCEDURE INSERTSOUSCATEGORIE(
     P_IDCATEGORIE IN SOUSCATEGORIE.IDCATEGORIE%TYPE,
	   P_TITRE IN SOUSCATEGORIE.TITRE%TYPE)
IS
BEGIN
  INSERT INTO SOUSCATEGORIE
  VALUES (SEQ_SOUSCATEGORIE.NEXTVAL, P_IDCATEGORIE, P_TITRE);
  
  COMMIT;
END;

-- Supression de l'ID car le titre suffit (Adrien - 12/12)
create or replace PROCEDURE DELETESOUSCATEGORIE(
     P_TITRE IN SOUSCATEGORIE.TITRE%TYPE)
IS
BEGIN
  DELETE FROM SOUSCATEGORIE
  WHERE P_TITRE = TITRE;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATESOUSCATEGORIE(
     P_IDSOUSCATEGORIE IN SOUSCATEGORIE.IDSOUSCATEGORIE%TYPE,
     P_IDCATEGORIE IN SOUSCATEGORIE.IDCATEGORIE%TYPE,
	   P_TITRE IN SOUSCATEGORIE.TITRE%TYPE)
IS
BEGIN
  UPDATE SOUSCATEGORIE
  SET TITRE = P_TITRE, IDCATEGORIE = P_IDCATEGORIE
  WHERE IDSOUSCATEGORIE = P_IDSOUSCATEGORIE;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTSOUSCATEGORIE(
     -- PARAMETRE ENTRANT
	   P_IDSOUSCATEGORIE IN SOUSCATEGORIE.IDSOUSCATEGORIE%TYPE,
     -- LES PARAMETRES SORTANTS
     O_IDCATEGORIE OUT SOUSCATEGORIE.IDCATEGORIE%TYPE,
	   O_TITRE OUT SOUSCATEGORIE.TITRE%TYPE)
IS
BEGIN
  SELECT IDCATEGORIE, TITRE
  INTO O_IDCATEGORIE, O_TITRE
  FROM SOUSCATEGORIE WHERE IDSOUSCATEGORIE = P_IDSOUSCATEGORIE;
END;

create or replace PROCEDURE GETLISTSOUSCATEGORIE(
	   CUR_SOUSCATEGORIE OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_SOUSCATEGORIE FOR
  SELECT * FROM SOUSCATEGORIE;
END;

/*==============================================================*/
/* PROCEDURES STOCKEES - SUJET                                  */
/*==============================================================*/
create or replace PROCEDURE INSERTSUJET(
	   --P_IDSUJET IN SUJET.IDSUJET%TYPE,
	   P_IDSOUSCATEGORIE IN SUJET.IDSOUSCATEGORIE%TYPE,
     P_TITRE IN SUJET.TITRE%TYPE,
     P_DATESUJET IN SUJET.DATESUJET%TYPE,
     P_IDUTILISATEUR IN SUJET.IDUTILISATEUR%TYPE)
IS
BEGIN
  INSERT INTO SUJET
  VALUES (SEQ_SUJET.NEXTVAL, P_IDSOUSCATEGORIE, P_TITRE, P_DATESUJET, P_IDUTILISATEUR);
  
  COMMIT;
END;

create or replace PROCEDURE DELETESUJET(
	   P_TITRE IN SUJET.TITRE%TYPE,
     P_DATESUJET IN SUJET.DATESUJET%TYPE)
IS
BEGIN
  DELETE FROM SUJET
  WHERE P_TITRE = TITRE AND P_DATESUJET = DATESUJET;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATESUJET(
     P_IDSUJET IN SUJET.IDSUJET%TYPE,
	   P_IDSOUSCATEGORIE IN SUJET.IDSOUSCATEGORIE%TYPE,
     P_TITRE IN SUJET.TITRE%TYPE,
     P_DATESUJET IN SUJET.DATESUJET%TYPE,
     P_IDUTILISATEUR IN SUJET.IDUTILISATEUR%TYPE)
IS
BEGIN
  UPDATE SUJET
  SET IDSOUSCATEGORIE = P_IDSOUSCATEGORIE, TITRE = P_TITRE, DATESUJET = P_DATESUJET, IDUTILISATEUR = P_IDUTILISATEUR
  WHERE IDSUJET = P_IDSUJET;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTSUJET(
     -- PARAMETRE ENTRANT
	   P_IDSUJET IN SUJET.IDSUJET%TYPE,
     -- LES PARAMETRES SORTANTS
	   O_IDSUJET OUT SUJET.IDSUJET%TYPE,
	   O_IDSOUSCATEGORIE OUT SUJET.IDSOUSCATEGORIE%TYPE,
	   O_TITRE OUT SUJET.TITRE%TYPE,
     O_DATESUJET OUT SUJET.DATESUJET%TYPE,
     O_IDUTILISATEUR OUT SUJET.IDUTILISATEUR%TYPE)
IS
BEGIN
  SELECT IDSUJET, IDSOUSCATEGORIE, TITRE, DATESUJET, IDUTILISATEUR
  INTO O_IDSUJET,  O_IDSOUSCATEGORIE, O_TITRE, O_DATESUJET, O_IDUTILISATEUR
  FROM SUJET WHERE IDSUJET = P_IDSUJET;
END;

create or replace PROCEDURE GETLISTSUJET(
	   CUR_SUJET OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_SUJET FOR
  SELECT * FROM SUJET;
END;

/*==============================================================*/
/* PROCEDURES STOCKEES - HISTORIQUE                             */
/*==============================================================*/
create or replace PROCEDURE INSERTHISTORIQUE(
	   --P_IDHISTORIQUE IN HISTORIQUE.IDHISTORIQUE%TYPE,
	   P_DATECONNEXION IN HISTORIQUE.DATECONNEXION%TYPE,
	   P_IDUTILISATEUR IN HISTORIQUE.IDUTILISATEUR%TYPE)
IS
BEGIN
  INSERT INTO HISTORIQUE
  VALUES (SEQ_HISTORIQUE.NEXTVAL, P_DATECONNEXION, P_IDUTILISATEUR);
  
  COMMIT;
END;

create or replace PROCEDURE DELETEHISTORIQUE(
	   P_DATECONNEXION IN HISTORIQUE.DATECONNEXION%TYPE,
     P_IDUTILISATEUR IN HISTORIQUE.IDUTILISATEUR%TYPE)
IS
BEGIN
  DELETE FROM HISTORIQUE
  WHERE P_DATECONNEXION = DATECONNEXION AND P_IDUTILISATEUR = IDUTILISATEUR;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATEHISTORIQUE(
      P_DATECONNEXION IN HISTORIQUE.DATECONNEXION%TYPE,
      P_IDUTILISATEUR IN HISTORIQUE.IDUTILISATEUR%TYPE,
      P_IDHISTORIQUE IN HISTORIQUE.IDHISTORIQUE%TYPE)
IS
BEGIN
  UPDATE HISTORIQUE
  SET DATECONNEXION = P_DATECONNEXION, IDUTILISATEUR = P_IDUTILISATEUR
  WHERE IDHISTORIQUE = P_IDHISTORIQUE;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTHISTORIQUE(
     -- PARAMETRE ENTRANT
	   P_IDHISTORIQUE IN HISTORIQUE.IDHISTORIQUE%TYPE,
     -- LES PARAMETRES SORTANTS
	   O_DATECONNEXION OUT HISTORIQUE.DATECONNEXION%TYPE,
	   O_IDUTILISATEUR OUT HISTORIQUE.IDUTILISATEUR%TYPE)
IS
BEGIN
  SELECT DATECONNEXION, IDUTILISATEUR
  INTO O_DATECONNEXION,  O_IDUTILISATEUR
  FROM HISTORIQUE WHERE IDHISTORIQUE = P_IDHISTORIQUE;
END;

create or replace PROCEDURE GETLISTHISTORIQUE(
	   CUR_HISTORIQUE OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_HISTORIQUE FOR
  SELECT * FROM HISTORIQUE;
END;

/*==============================================================*/
/* PROCEDURES STOCKEES - COMMENTAIRE                            */
/*==============================================================*/
create or replace PROCEDURE INSERTCOMMENTAIRE(
	   --P_IDCOMMENTAIRE IN COMMENTAIRE.IDCOMMENTAIRE%TYPE,
	   P_IDSUJET IN COMMENTAIRE.IDSUJET%TYPE,
	   P_TEXTE IN COMMENTAIRE.TEXTE%TYPE,
     P_DATECOMMENTAIRE IN COMMENTAIRE.DATECOMMENTAIRE%TYPE,
     P_IDUTILISATEUR IN COMMENTAIRE.IDUTILISATEUR%TYPE)
IS
BEGIN
  INSERT INTO COMMENTAIRE
  VALUES (SEQ_COMMENTAIRE.NEXTVAL, P_IDSUJET, P_TEXTE, P_DATECOMMENTAIRE, P_IDUTILISATEUR);
  
  COMMIT;
END;

create or replace PROCEDURE DELETECOMMENTAIRE(
	   P_TEXTE IN COMMENTAIRE.TEXTE%TYPE,
     P_DATECOMMENTAIRE IN COMMENTAIRE.DATECOMMENTAIRE%TYPE)
IS
BEGIN
  DELETE FROM COMMENTAIRE
  WHERE P_TEXTE = TEXTE AND P_DATECOMMENTAIRE = DATECOMMENTAIRE;
  
  COMMIT;
END;

create or replace PROCEDURE UPDATECOMMENTAIRE(
	   P_TEXTE IN COMMENTAIRE.TEXTE%TYPE,
     P_DATECOMMENTAIRE IN COMMENTAIRE.DATECOMMENTAIRE%TYPE,
     P_IDCOMMENTAIRE IN COMMENTAIRE.IDCOMMENTAIRE%TYPE)
IS
BEGIN
  UPDATE COMMENTAIRE
  SET TEXTE = P_TEXTE, DATECOMMENTAIRE = P_DATECOMMENTAIRE
  WHERE IDCOMMENTAIRE = P_IDCOMMENTAIRE;
  
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SELECTCOMMENTAIRE(
     -- PARAMETRE ENTRANT
	   P_IDCOMMENTAIRE IN COMMENTAIRE.IDCOMMENTAIRE%TYPE,
     -- LES PARAMETRES SORTANTS
	   O_IDSUJET OUT COMMENTAIRE.IDSUJET%TYPE,
	   O_TEXTE OUT COMMENTAIRE.TEXTE%TYPE,
	   O_DATECOMMENTAIRE OUT COMMENTAIRE.DATECOMMENTAIRE%TYPE,
     O_IDUTILISATEUR OUT COMMENTAIRE.IDUTILISATEUR%TYPE)
IS
BEGIN
  SELECT IDSUJET, TEXTE, DATECOMMENTAIRE, IDUTILISATEUR
  INTO O_IDSUJET,  O_TEXTE, O_DATECOMMENTAIRE, O_IDUTILISATEUR
  FROM COMMENTAIRE WHERE IDCOMMENTAIRE = P_IDCOMMENTAIRE;
END;
/

create or replace PROCEDURE GETLISTCOMMENTAIRE(
	   CUR_COMMENTAIRE OUT SYS_REFCURSOR)
IS
BEGIN
  --On crée un curseur
  OPEN CUR_COMMENTAIRE FOR
  SELECT * FROM COMMENTAIRE;
END;
